### PR TITLE
8 feature 8 login feature

### LINKED ISSUE #8: [Feature 8] <Login Feature>

### PR DESCRIPTION
**Pull request by ggykwong**
Implemented LoginInteractor.

### CODE REVIEW

**Comment by yeludan** [comment]
I think instead of returning boolean for validateLogin, we can make it return int, so that the view can do its job. Here's some code I wrote for your reference.

public int validateLogin(String username, String password) {
    if (!(accounts.containsKey(username))) {
        return 2;
    }
    else if (!(Objects.equals(accounts.get(username), password))) {
        return 3;
    }
    else {
        return 1;
    };

Same for createAccount. It can return int (1, 2, and 3).

**Comment by ggykwong** [comment]
I have just pushed new edits to validateLogin and createAccount.

**Comment by yeludan** [comment]
(1)
I add sound button in my 4 login GUIs. Do you think we need to play a sound clip while in these home pages before we start a game?
If so, do we take these GUIs as an event, maybe called "home event"?

(2)
Since TA asked us to slip Controller and Presenter, may add another instance variable in LoginInteractor:

Presenter presenter;

validateLogin and createAccount methods may be changed as follows:

public void validateLogin(String username, String password) {
        // an account with this username does not exist
        if (!(accounts.containsKey(username))) {
            presenter.updateLogin(2, username);
        }
        // password does not match username
        else if (!(Objects.equals(accounts.get(username), password))) {
            presenter.updateLogin(3, username);
        }
        // login is successful
        else {
            this.currentUser = username;
            presenter.updateLogin(3, username);
        }
    }

public void createAccount(String username, String password1, String password2) {
        // case that username is unique, password is long enough, and passwords match
        if (validateNewUsername(username) && validateNewPassword(password1) && (password1.equals(password2))) {
            try {
                // create new FileWriter
                FileWriter fw = new FileWriter(filepath, true);
                fw.write("\n" + username + "," + password1);
                fw.close();
                // update <accounts> so that LoginInteractor doesn't have to be reconstructed
                accounts.put(username, password1);
                presenter.updateRegister(1, username);
            }
            catch (IOException e) { e.printStackTrace(); }
        }
        // case that username already exists
        else if (!(validateNewUsername(username))) { presenter.updateRegister(2, username); }
        // case that passwords do not match
        else if (!Objects.equals(password1, password2)) { presenter.updateRegister(3, username); }
        // case that passwords match but password is too short
        else if (!(validateNewPassword(password1))) { presenter.updateRegister(4, username); }
        // some other case is true
        presenter.updateRegister(5, username);
    }

**Comment by ggykwong** [comment]
(1) [Resolved offline and decided to hard-code sound in main file instead of making an event for home screen.]

**Comment by ggykwong** [comment]
(2) Just made the edits you suggested.

**Review by yeludan — APPROVED** [review]
ready for merging

**Pull request merged**
