### PR TITLE
4 feature 1 save feature

### LINKED ISSUE #4: [Feature 1] <Save Feature>
A save system that allows users to save their progress in the game and reload their data each time they return to the game.

### PR DESCRIPTION
**Pull request by alainahu**
Created the save interface, load interface, save interactor, load interactor, and a test file. However, my gradle files and some additional files were pushed with it. These files should not be selected when merging. The save feature files are Saver, Loader, SaveInteractor, and LoadInteractor. 

UPDATE: Issue fixed! I removed the unnecessary files.

### CODE REVIEW

**Comment by ggykwong** [comment]
I have started to look through your two classes. LoadInteractor and SaveInteractor may each need a constructor so that their methods can be accessed. Will finish looking at the methods and interfaces and get back to you!

**Comment by ggykwong** [comment]
Finished reviewing, and everything else checks out.

**Comment by ggykwong** [comment]
saveToFile takes an Object for the second parameter. Do you want to restrict it to PlayerData objects since the Interactors only use this type?

**Comment by ggykwong** [comment]
The way saveToFile is implemented, it seems like there's a precondition that there is an existing file at filePath. Which class creates the file for a user whose data hasn't been saved yet? Also, which class remembers the filePath that belongs to each user (relevant for readFromFile and saveToFile's filePath parameters)? Would we need to create more dependencies on PlayerData?

**Comment by alainahu** [comment]
> 
I just changed the second parameter of saveToFile to be a PlayerData object. Thanks for the suggestion!

saveToFile automatically writes the ser file to the location we specify as the filepath parameter. To remember where each user's player is saved, we are using the user's username that's stored in PlayerData to be the file name. I've attached a few screenshots of the tests I ran.
Screen Shot 2022-11-25 at 4 26 01 PM
Screen Shot 2022-11-25 at 4 26 13 PM
Screen Shot 2022-11-25 at 4 26 55 PM

**Review by ggykwong — DISMISSED** [review]
I see your changes, and thanks for the explanation. Seems like everything checks out now!

**Review by ggykwong — APPROVED** [review]
Ready for merging.

**Pull request merged**
